/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 26 22:20:02 GMT 2022
 */

package example;

import org.junit.Test;
import static org.junit.Assert.*;
import example.App;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

// @RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class App_ESTest extends App_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      App app0 = new App();
      String string0 = app0.down();
      assertEquals("[Fri Feb 14 20:21:21 GMT 2014] > Applicativo DOWN", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      App app0 = new App();
      String string0 = app0.up();
      assertEquals("[Fri Feb 14 20:21:21 GMT 2014] > Applicativo UP", string0);
  }
}
