/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 26 22:19:02 GMT 2022
 */

package example.app.models;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import example.Types.Climas;
import example.app.models.Destino;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

// @RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Destino_ESTest extends Destino_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Climas climas0 = Climas.CHUVOSO;
      Double double0 = new Double(1.0);
      Destino destino0 = new Destino("v?AN2Q/CTBc5qq", integer0, climas0, double0);
      ArrayList<String> arrayList0 = new ArrayList<String>();
      destino0.setAtracoes(arrayList0);
      assertFalse(destino0.getCidadeTuristica());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Integer integer0 = new Integer(1);
      Climas climas0 = Climas.TEMPESTUOSO;
      Double double0 = new Double(1);
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Destino destino0 = new Destino("CHUVOSO", integer0, climas0, double0, arrayList0);
      Double double1 = new Double(1);
      destino0.setPreco(double1);
      assertEquals((double)double1, (double)double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Integer integer0 = new Integer(898);
      Climas climas0 = Climas.AGRADAVEL;
      Double double0 = new Double(241.13417);
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Destino destino0 = new Destino("5(`M2SL4][&MS", integer0, climas0, double0, arrayList0);
      destino0.adicionaAtracao("5(`M2SL4][&MS");
      destino0.removeAtracao((-1));
      assertEquals(241.13417, destino0.getPreco(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Integer integer0 = new Integer(1);
      Climas climas0 = Climas.VENTANIA;
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Destino destino0 = new Destino("+X<t_<&]", integer0, climas0, (Double) null, arrayList0);
      Double double0 = destino0.getPreco();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Integer integer0 = new Integer((-488));
      Climas climas0 = Climas.ENSOLARADO;
      Double double0 = new Double((-488));
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Destino destino0 = new Destino("example.app.models.Destino", integer0, climas0, double0, arrayList0);
      Double double1 = destino0.getPreco();
      assertEquals((-488.0), (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Double double0 = new Double(0.0);
      Climas climas0 = Climas.CHUVOSO;
      Destino destino0 = new Destino("wx DbX(+a&Ud7[1Q", (Integer) null, climas0, (Double) null, arrayList0);
      destino0.preco = double0;
      Double double1 = destino0.getPreco();
      assertEquals(0.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Integer integer0 = new Integer((-2376));
      Climas climas0 = Climas.VENTANIA;
      Double double0 = new Double(187.6725);
      Destino destino0 = new Destino((String) null, integer0, climas0, double0);
      Double double1 = destino0.getPreco();
      assertNotNull(double1);
      assertFalse(destino0.getCidadeTuristica());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Climas climas0 = Climas.TEMPESTUOSO;
      Double double0 = new Double(0.0);
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Destino destino0 = new Destino("", (Integer) null, climas0, double0, arrayList0);
      Boolean boolean0 = destino0.getCidadeTuristica();
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Integer integer0 = new Integer(662);
      Climas climas0 = Climas.ENSOLARADO;
      Double double0 = new Double(0.0);
      Destino destino0 = new Destino((String) null, integer0, climas0, double0);
      assertFalse(destino0.getCidadeTuristica());
      
      Boolean boolean0 = Boolean.valueOf(true);
      destino0.setCidadeTuristica(boolean0);
      destino0.getCidadeTuristica();
      assertTrue(destino0.getCidadeTuristica());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Climas climas0 = Climas.CHUVOSO;
      Double double0 = new Double(2084);
      Destino destino0 = new Destino("/|", (Integer) null, climas0, double0);
      destino0.getAtracoes();
      assertFalse(destino0.getCidadeTuristica());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Integer integer0 = new Integer(1);
      Climas climas0 = Climas.TEMPESTUOSO;
      Double double0 = new Double(1);
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Destino destino0 = new Destino("CHUVOSO", integer0, climas0, double0, arrayList0);
      destino0.adicionaAtracao((String) null);
      ArrayList<String> arrayList1 = destino0.getAtracoes();
      assertFalse(arrayList1.contains("CHUVOSO"));
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Integer integer0 = new Integer((-1106));
      Climas climas0 = Climas.AGRADAVEL;
      Double double0 = new Double((-982.9847914361264));
      Destino destino0 = new Destino("example.app.models.Cidade", integer0, climas0, double0);
      // Undeclared exception!
      try { 
        destino0.removeAtracao((-635));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("example.app.models.Destino", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Climas climas0 = Climas.TEMPESTUOSO;
      Double double0 = new Double(0.0);
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Destino destino0 = new Destino("", (Integer) null, climas0, double0, arrayList0);
      // Undeclared exception!
      try { 
        destino0.removeAtracao((-1327));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Integer integer0 = new Integer(5317);
      Climas climas0 = Climas.VENTANIA;
      Double double0 = new Double(5317);
      Destino destino0 = null;
      try {
        destino0 = new Destino("", integer0, climas0, double0, (ArrayList<String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("example.app.models.Destino", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ArrayList<String> arrayList0 = new ArrayList<String>();
      arrayList0.add("");
      arrayList0.add((String) null);
      arrayList0.add("");
      arrayList0.add("");
      arrayList0.add("~~LOk|W6");
      arrayList0.add("wx DbX(+a&Ud7[1Q");
      Climas climas0 = Climas.CHUVOSO;
      Destino destino0 = new Destino("wx DbX(+a&Ud7[1Q", (Integer) null, climas0, (Double) null, arrayList0);
      assertTrue(destino0.getCidadeTuristica());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Integer integer0 = new Integer(1);
      Climas climas0 = Climas.TEMPESTUOSO;
      Double double0 = new Double(1);
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Destino destino0 = new Destino("CHUVOSO", integer0, climas0, double0, arrayList0);
      // Undeclared exception!
      try { 
        destino0.removeAtracao(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 1, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Integer integer0 = new Integer(1);
      Climas climas0 = Climas.TEMPESTUOSO;
      Double double0 = new Double(1);
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Destino destino0 = new Destino("CHUVOSO", integer0, climas0, double0, arrayList0);
      ArrayList<String> arrayList1 = destino0.getAtracoes();
      assertSame(arrayList0, arrayList1);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Integer integer0 = new Integer((-1592));
      Climas climas0 = Climas.ENSOLARADO;
      Double double0 = new Double(0.0);
      Destino destino0 = new Destino("Cd1-v '", integer0, climas0, double0);
      // Undeclared exception!
      try { 
        destino0.adicionaAtracao("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("example.app.models.Destino", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Climas climas0 = Climas.CHUVOSO;
      Double double0 = new Double(2084);
      Destino destino0 = new Destino("/|", (Integer) null, climas0, double0);
      Boolean boolean0 = destino0.getCidadeTuristica();
      assertFalse(boolean0);
  }
}
