/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 26 22:19:13 GMT 2022
 */

package example.app.models;

import org.junit.Test;
import static org.junit.Assert.*;
import example.app.models.Pessoa;


// @RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Pessoa_ESTest2 extends Pessoa_ESTest_scaffolding {


  @Test(timeout = 4000)
  public void getNomeTest() throws Throwable  {
      Pessoa pessoa0 = new Pessoa("", 20);
      String string0 = pessoa0.getNome();
      assertEquals("", string0);
  }


}
