/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 26 22:18:00 GMT 2022
 */

package example.app.models;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import example.app.models.Carteira;
import example.app.models.Cliente;
import example.app.models.Empresa;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Empresa_ESTest extends Empresa_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("9qa^i^a/4;SGy", (-2.2608748977453477), hashMap0);
      Cliente cliente0 = new Cliente("9qa^i^a/4;SGy", 3749, "9qa^i^a/4;SGy", "9qa^i^a/4;SGy");
      empresa0.adicionaCliente(cliente0);
      ArrayList<Cliente> arrayList0 = empresa0.listaTodosClientesInativos();
      assertEquals((-2.2608748977453477), empresa0.getCaixa(), 0.01);
      assertFalse(arrayList0.contains(cliente0));
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("n[>;n,\"oV(UzKEMC.Z", 1285.07203100387, hashMap0);
      Carteira carteira0 = new Carteira(1285.07203100387, 1285.07203100387, 1285.07203100387);
      Cliente cliente0 = new Cliente("n[>;n,\"oV(UzKEMC.Z", 21, "n[>;n,\"oV(UzKEMC.Z", "n[>;n,\"oV(UzKEMC.Z", carteira0);
      Boolean boolean0 = Boolean.valueOf("n[>;n,\"oV(UzKEMC.Z");
      hashMap0.put(cliente0, boolean0);
      ArrayList<Cliente> arrayList0 = empresa0.listaTodosClientesAtivos();
      assertFalse(arrayList0.contains(cliente0));
      assertEquals(1285.07203100387, empresa0.getCaixa(), 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("", hashMap0);
      HashMap<Cliente, Boolean> hashMap1 = new HashMap<Cliente, Boolean>(226, 226);
      empresa0.setClientes(hashMap1);
      assertEquals(0.0, empresa0.getCaixa(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa((String) null, 0.0, hashMap0);
      empresa0.getNome();
      assertEquals(0.0, empresa0.getCaixa(), 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("", (-1900.3841), hashMap0);
      String string0 = empresa0.getNome();
      assertEquals((-1900.3841), empresa0.getCaixa(), 0.01);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Empresa empresa0 = new Empresa("", (Map<Cliente, Boolean>) null);
      empresa0.getClientes();
      assertEquals(0.0, empresa0.getCaixa(), 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("TB[E?\"W_wvfU", hashMap0);
      Cliente cliente0 = new Cliente("", 21, "example.app.models.Empresa", "", (Carteira) null);
      empresa0.adicionaCliente(cliente0);
      empresa0.getClientes();
      assertEquals(0.0, empresa0.getCaixa(), 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Empresa empresa0 = new Empresa("uULRcy-", (Map<Cliente, Boolean>) null);
      double double0 = empresa0.getCaixa();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("P,#G", (-1.0), hashMap0);
      double double0 = empresa0.getCaixa();
      assertEquals((-1.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("TB[E?\"W_wvfU", hashMap0);
      Cliente cliente0 = new Cliente("", 21, "example.app.models.Empresa", "", (Carteira) null);
      Boolean boolean0 = new Boolean(true);
      hashMap0.put(cliente0, boolean0);
      empresa0.buscaCliente(cliente0);
      assertEquals(0.0, empresa0.getCaixa(), 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Empresa empresa0 = new Empresa("S", 957.482814242, (Map<Cliente, Boolean>) null);
      Carteira carteira0 = new Carteira(0, 0, 0.0);
      Cliente cliente0 = new Cliente("}YR=,ddq.lk:(HQsj", 0, "3'1)DWuF!7xWhxZn>", "}YR=,ddq.lk:(HQsj", carteira0);
      // Undeclared exception!
      try { 
        empresa0.removeCliente(cliente0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("example.app.models.Empresa", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("", 0.0, hashMap0);
      Boolean boolean0 = new Boolean("example.app.models.Cliente");
      hashMap0.put((Cliente) null, boolean0);
      // Undeclared exception!
      try { 
        empresa0.listaTodosClientesAtivos();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("example.app.models.Empresa", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Empresa empresa0 = new Empresa("]1)ZWIN|@j=", (-1249.0873), (Map<Cliente, Boolean>) null);
      // Undeclared exception!
      try { 
        empresa0.listaTodosClientes();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("example.app.models.Empresa", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("`wAnG<PdzOk", hashMap0);
      Carteira carteira0 = new Carteira(0, 4618.8836, 4618.8836);
      Cliente cliente0 = new Cliente("^", 0, "^", "?K", carteira0);
      // Undeclared exception!
      try { 
        empresa0.buscaClienteAtivo(cliente0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("example.app.models.Empresa", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Empresa empresa0 = new Empresa("uULRcy-", (Map<Cliente, Boolean>) null);
      Carteira carteira0 = new Carteira(1274.862, 1.0, (-2609.2058285026246));
      Cliente cliente0 = new Cliente("uULRcy-", (-1), "uULRcy-", "uULRcy-", carteira0);
      // Undeclared exception!
      try { 
        empresa0.buscaCliente(cliente0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("example.app.models.Empresa", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa((String) null, 0.0, hashMap0);
      // Undeclared exception!
      try { 
        empresa0.adicionaCliente((Cliente) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("example.app.models.Empresa", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("TB[E?\"W_wvfU", hashMap0);
      Cliente cliente0 = new Cliente("", 20, "TB[E?\"W_wvfU", "");
      Boolean boolean0 = new Boolean(true);
      hashMap0.put(cliente0, boolean0);
      ArrayList<Cliente> arrayList0 = empresa0.listaTodosClientesInativos();
      assertEquals(0.0, empresa0.getCaixa(), 0.01);
      assertTrue(arrayList0.contains(cliente0));
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("TB[E?\"W_wvfU", hashMap0);
      Cliente cliente0 = new Cliente("", 21, "example.app.models.Empresa", "", (Carteira) null);
      empresa0.adicionaCliente(cliente0);
      ArrayList<Cliente> arrayList0 = empresa0.listaTodosClientesInativos();
      assertFalse(arrayList0.contains(cliente0));
      assertEquals(0.0, empresa0.getCaixa(), 0.01);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa((String) null, 1.5874623117978444, hashMap0);
      Cliente cliente0 = new Cliente((String) null, (-6), (String) null, (String) null);
      empresa0.adicionaCliente(cliente0);
      ArrayList<Cliente> arrayList0 = empresa0.listaTodosClientesAtivos();
      assertEquals(1.5874623117978444, empresa0.getCaixa(), 0.01);
      assertFalse(arrayList0.contains(cliente0));
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("n:^1s:EBM'RLm7", hashMap0);
      Cliente cliente0 = new Cliente("n:^1s:EBM'RLm7", 20, "n:^1s:EBM'RLm7", "n:^1s:EBM'RLm7");
      Boolean boolean0 = new Boolean(true);
      hashMap0.put(cliente0, boolean0);
      empresa0.listaTodosClientes();
      assertEquals(0.0, empresa0.getCaixa(), 0.01);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("TB[E?\"W_wvfU", hashMap0);
      empresa0.listaTodosClientes();
      assertEquals(0.0, empresa0.getCaixa(), 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("TB[E?\"W_wvfU", hashMap0);
      Cliente cliente0 = new Cliente("", 21, "example.app.models.Empresa", "", (Carteira) null);
      Boolean boolean0 = new Boolean(true);
      hashMap0.put(cliente0, boolean0);
      Boolean boolean1 = empresa0.buscaClienteAtivo(cliente0);
      assertTrue(boolean1);
      assertEquals(0.0, empresa0.getCaixa(), 0.01);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa((String) null, (-3457.176), hashMap0);
      Cliente cliente0 = new Cliente((String) null, (-177), (String) null, (String) null);
      Boolean boolean0 = empresa0.buscaCliente(cliente0);
      assertNotNull(boolean0);
      
      hashMap0.put(cliente0, boolean0);
      Boolean boolean1 = empresa0.buscaClienteAtivo(cliente0);
      assertFalse(boolean1);
      assertEquals((-3457.176), empresa0.getCaixa(), 0.01);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("<q+ t*9k6", hashMap0);
      Boolean boolean0 = empresa0.buscaCliente((Cliente) null);
      hashMap0.put((Cliente) null, boolean0);
      // Undeclared exception!
      try { 
        empresa0.listaTodosClientesInativos();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("example.app.models.Empresa", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("9qa^i^a/4;SGy", (-2.2608748977453477), hashMap0);
      Cliente cliente0 = new Cliente("9qa^i^a/4;SGy", 3749, "9qa^i^a/4;SGy", "9qa^i^a/4;SGy");
      empresa0.adicionaCliente(cliente0);
      ArrayList<Cliente> arrayList0 = empresa0.listaTodosClientesAtivos();
      assertEquals((-2.2608748977453477), empresa0.getCaixa(), 0.01);
      assertTrue(arrayList0.contains(cliente0));
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("9qa^i^a/4;SGy", (-2.2608748977453477), hashMap0);
      Cliente cliente0 = new Cliente("9qa^i^a/4;SGy", 3749, "9qa^i^a/4;SGy", "9qa^i^a/4;SGy");
      empresa0.removeCliente(cliente0);
      assertEquals((-2.2608748977453477), empresa0.getCaixa(), 0.01);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("9qa^i^a/4;SGy", (-2.2608748977453477), hashMap0);
      String string0 = empresa0.getNome();
      assertNotNull(string0);
      assertEquals((-2.2608748977453477), empresa0.getCaixa(), 0.01);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("TB[E?\"W_wvfU", hashMap0);
      empresa0.setNome("TB[E?\"W_wvfU");
      assertEquals(0.0, empresa0.getCaixa(), 0.01);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("TB[E?\"W_wvfU", hashMap0);
      assertEquals(0.0, empresa0.getCaixa(), 0.01);
      
      empresa0.setCaixa(1.0);
      assertEquals(1.0, empresa0.getCaixa(), 0.01);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa((String) null, 1.5874623117978444, hashMap0);
      double double0 = empresa0.getCaixa();
      assertEquals(1.5874623117978444, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      HashMap<Cliente, Boolean> hashMap0 = new HashMap<Cliente, Boolean>();
      Empresa empresa0 = new Empresa("TB[E?\"W_wvfU", hashMap0);
      Map<Cliente, Boolean> map0 = empresa0.getClientes();
      assertNotNull(map0);
      assertEquals(0.0, empresa0.getCaixa(), 0.01);
  }
}
